### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by frank-deng**
1. Removed some files with unnecessary executable permission under Linux.
2. Use `sscanf()` to parse time information of CUE file, so as to correctly handle tracks with time information like below instead of generating a zero-length song:
```
FILE "audiocd.dat" BINARY
  TRACK 01 AUDIO
    INDEX 01 0:00:00
  TRACK 02 AUDIO
    INDEX 01 1:59:43
```

### CODE REVIEW

**Comment by AZO234** [comment]
Thanks!
I think sscan's filter "%2d:%2d:%2d" is better.  
And if input is illegal format string, check sscan's return value is EOF, then return 0;

**Comment by frank-deng** [comment]
Thank you for your suggestion.

**Comment by frank-deng** [comment]
It seems that under Ubuntu 16.04, `sscanf(str, "%2d:%2d:%2d", &m, &s, &f)` will return 3 when str is legal, with other return values when str is illegal.

**Comment by AZO234** [comment]
Yeah. Nice work!

**Pull request merged**
