### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by frank-deng**
Removed unnessesary executable permissions on some files under Linux.

### CODE REVIEW

**Comment by AZO234** [comment]
Thanks! There are some questions.

1st.
I can build NP2kai X11 version, no link error.

2nd.
NP2kai's X11 has two features.
* CPU 286 (without --enable-ia32)
* CPU 386 (with --enable-ia32)
I think writing --enable-ia32 in line 44 of README.md is unnecessary.

**Comment by frank-deng** [comment]
When I tried to run `autogen.sh` without adding `export CFLAGS='-pthread'` and `export LDFLAGS='-pthread'`, I got the following errors while linking:

```
/usr/bin/ld: ./../x11/misc/xnp2-threadbase.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```
My OS is Ubuntu 16.04.

**Comment by AZO234** [comment]
I use Ubuntu 16.04 too. (I use GNOME Edition.)
Link options about ’pthread’ are generated automatically.

**Comment by frank-deng** [comment]
Under X11 directory, when I run `./autogen.sh` then `./configure`, I found the following error message during configure:
```
ACX_PTHREAD: command not found
```

**Pull request closed without merging**
