### PR TITLE
Add manual for 640x480x256 support under Windows 3.1

### PR DESCRIPTION
**Pull request by frank-deng**

### CODE REVIEW

**Comment by AZO234** [comment]
PEGC is PC-98 internal graphic ability.
(640x480x256 without WAB)

The thing that succeeded this time is WAB(external Window Accelerator Board).

**Comment by frank-deng** [comment]
Thanks!

**Comment by frank-deng** [comment]
Is it appropriate to move PEGC related manual to the position before WAB?

**Comment by AZO234** [comment]
Thanks to your writing!!

**Pull request merged**
