### PR TITLE
Implement fullscreen mode for SDL2 and CMakeLists.txt fixes

### PR DESCRIPTION
**Pull request by john-at-charpa**
Greetings! Thank you for your excellent work on NP2. NP2kai is the only version I've found that builds easily on macOS. 

I noticed that the SDL2 code lacks a full screen option, so I've implemented it. I also added logic for the menu options. For macOS users there is also an added cmd-f toggle. 

After cloning and trying to build I noticed that some of the CMakeLists.txt logic (in particular the git related logic) returns confusing errors. I've reworked it to return more specific errors. 
- Check for the git binary and fail if it does not work
- Fall back on the cmake project version for the git tag if a tag does not exist (a cloned repo won't have a tag)
- Optionally tell the user why it failed and suggest the git tag command 

Here is the change log:

o Implement fullscreen mode for SDL2 with a working menu (F11/mouse) 
o Implement a cmd-f fullscreen toggle for macOS
o Improve git logic in CMakeLists.txt
  - Rework git detection and tag usage logic
  - Make error messages clearer with fix suggestions
  - Fall back on the cmake project version if no git tag is found (clone)
  - Do not hard code OpenSSL paths unless they exist

是非PRのご使用をご検討ください。よろしくお願い致します。

### CODE REVIEW

**Comment by AZO234** [comment]
OK. I merge this.

**Comment by cmitu** [comment]
After this merge, the Libretro core build seems to have been broken, failing to compile with:
```
....
cc -c -o../sdl/sysmenu.o ../sdl/sysmenu.c  -mcpu=cortex-a72 -O2 -DNP2KAI_GIT_TAG=\"master\" -DNP2KAI_GIT_HASH=\"da21965\" -fsigned-char -fPIC -D__LIBRETRO__  -pedantic -Wall -Wextra -Wformat -Wformat-security  -Wno-overflow -fno-strict-overflow -Werror=format-security -O2 -DNDEBUG -D_NDEBUG -D_FORTIFY_SOURCE=2 -fstack-protector -DNST_NO_ZLIB -I.. -I../cbus -I../common -I../diskimage -I../diskimage/cd -I../diskimage/fd -I../embed -I../embed/menu -I../embed/menubase -I../fdd -I../font -I../generic -I../io -I../mem -I../sound -I../sound/vermouth -I../sound/mame -I../sound/fmgen -I../trap -I../vram -I../wab -I../sdl -I../sdl/libretro -I../sdl/libretro/libretro-common/include -I../sdl/libretro/libretro-common/include/array -I../sdl/libretro/libretro-common/include/audio -I../sdl/libretro/libretro-common/include/audio/conversion -I../sdl/libretro/libretro-common/include/compat -I../sdl/libretro/libretro-common/include/dynamic -I../sdl/libretro/libretro-common/include/encodings -I../sdl/libretro/libretro-common/include/features -I../sdl/libretro/libretro-common/include/file -I../sdl/libretro/libretro-common/include/formats -I../sdl/libretro/libretro-common/include/gfx -I../sdl/libretro/libretro-common/include/gfx/math -I../sdl/libretro/libretro-common/include/gfx/scaler -I../sdl/libretro/libretro-common/include/glsm -I../sdl/libretro/libretro-common/include/glsym -I../sdl/libretro/libretro-common/include/glsym/switch -I../sdl/libretro/libretro-common/include/libchdr -I../sdl/libretro/libretro-common/include/lists -I../sdl/libretro/libretro-common/include/math -I../sdl/libretro/libretro-common/include/net -I../sdl/libretro/libretro-common/include/queues -I../sdl/libretro/libretro-common/include/rthreads -I../sdl/libretro/libretro-common/include/streams -I../sdl/libretro/libretro-common/include/string -I../sdl/libretro/libretro-common/include/utils -I../sdl/libretro/libretro-common/include/vfs -I../sdl/libretro/libretro-common/include/vulkan -I../i386c -I../i386c/ia32 -I../i386c/ia32/instructions -I../i386c/ia32/instructions/fpu  -DBIOS_IO_EMULATION -DOSLANG_UTF8 -DOSLINEBREAK_CRLF -DSOUND_CRITICAL -DSUPPORT_16BPP -DSUPPORT_24BPP -DSUPPORT_32BPP -DSUPPORT_8BPP -DSUPPORT_BMS -DSUPPORT_CL_GD5430 -DSUPPORT_CRT15KHZ -DSUPPORT_DEBUGSS -DSUPPORT_FAST_MEMORYCHECK -DSUPPORT_FMGEN -DSUPPORT_GPIB -DSUPPORT_HOSTDRV -DSUPPORT_HRTIMER -DSUPPORT_IDEIO -DSUPPORT_KAI_IMAGES -DSUPPORT_LARGE_HDD -DSUPPORT_NORMALDISP -DSUPPORT_PC9861K -DSUPPORT_PX -DSUPPORT_RESUME -DSUPPORT_RS232C_FIFO -DSUPPORT_S98 -DSUPPORT_SCSI -DSUPPORT_SMPU98 -DSUPPORT_SOFTKBD=0 -DSUPPORT_SOUND_SB16 -DSUPPORT_SWSEEKSND -DSUPPORT_SWWABRLYSND -DSUPPORT_STATSAVE=10 -DSUPPORT_UTF8 -DSUPPORT_V30EXT -DSUPPORT_V30ORIGINAL -DSUPPORT_VIDEOFILTER -DSUPPORT_VPCVHD -DSUPPORT_WAB -DUSE_MAME -DVAEG_FIX -DVERMOUTH_LIB -DCPUCORE_IA32 -DIA32_PAGING_EACHSIZE -DIA32_REBOOT_ON_PANIC -DSUPPORT_CRT31KHZ -DSUPPORT_FPU_DOSBOX -DSUPPORT_FPU_DOSBOX2 -DSUPPORT_FPU_SOFTFLOAT -DSUPPORT_GAMEPORT -DSUPPORT_MEMDBG32 -DSUPPORT_LARGE_MEMORY -DSUPPORT_PC9801_119 -DSUPPORT_PC9821 -DSUPPORT_PCI -DSUPPORT_PEGC -DSUPPORT_SOUND_SB16 -DSUPPORT_VGA_MODEX -DUSE_3DNOW -DUSE_FASTPAGING -DUSE_FPU -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -DUSE_SSE3 -DUSE_SSSE3 -DUSE_SSE4_1 -DUSE_SSE4_2 -DUSE_SSE4A -DUSE_TSC -DUSE_VME -std=gnu99
../sdl/np2.c: At top level:
../sdl/np2.c:809:13: warning: ‘np2exec’ defined but not used [-Wunused-function]
  809 | static void np2exec()
      |             ^~~~~~~
../sdl/np2.c:118:25: warning: ‘datadir’ defined but not used [-Wunused-variable]
  118 | static  char            datadir[3] = "/";
      |                         ^~~~~~~
../sdl/np2.c:114:25: warning: ‘lateframecount’ defined but not used [-Wunused-variable]
  114 | static  UINT            lateframecount; // フレーム遅れ数
      |                         ^~~~~~~~~~~~~~
../sdl/np2.c:52:19: warning: ‘appname’ defined but not used [-Wunused-const-variable=]
   52 | static const char appname[] =
      |                   ^~~~~~~
../sdl/soundmng.c: In function ‘soundmng_create’:
../sdl/soundmng.c:259:17: warning: unused variable ‘s’ [-Wunused-variable]
  259 |         UINT    s;
      |                 ^
../sdl/scrnmng.c: In function ‘scrnmng_create’:
../sdl/soundmng.c:256:33: warning: unused parameter ‘bufmsec’ [-Wunused-parameter]
  256 | soundmng_create(UINT rate, UINT bufmsec)
      |                            ~~~~~^~~~~~~
../sdl/scrnmng.c:162:25: warning: implicit declaration of function ‘SDL_SetWindowFullscreen’ [-Wimplicit-function-declaration]
  162 |                         SDL_SetWindowFullscreen(s_window, SDL_WINDOW_FULLSCREEN_DESKTOP);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
../sdl/scrnmng.c:162:49: error: ‘s_window’ undeclared (first use in this function)
  162 |                         SDL_SetWindowFullscreen(s_window, SDL_WINDOW_FULLSCREEN_DESKTOP);
      |                                                 ^~~~~~~~
...
```

**Comment by sl1pkn07** [comment]
for me failing on linux with

```
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c: In function 'amd98_bind':
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:475:32: error: passing argument 2 of 'iocore_attachout' from incompatible pointer type [-Wincompatible-pointer-types]
  475 |         iocore_attachout(0xd8, amd_od8);
      |                                ^~~~~~~
      |                                |
      |                                void (*)(UINT,  UINT8) {aka void (*)(unsigned int,  unsigned char)}
In file included from /tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:10:
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:107:43: note: expected 'IOOUT' {aka 'void (*)(unsigned int,  unsigned int)'} but argument is of type 'void (*)(UINT,  UINT8)' {aka 'void (*)(unsigned int,  unsigned char)'}
  107 | BRESULT iocore_attachout(UINT port, IOOUT func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:476:32: error: passing argument 2 of 'iocore_attachout' from incompatible pointer type [-Wincompatible-pointer-types]
  476 |         iocore_attachout(0xd9, amd_od9);
      |                                ^~~~~~~
      |                                |
      |                                void (*)(UINT,  UINT8) {aka void (*)(unsigned int,  unsigned char)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:107:43: note: expected 'IOOUT' {aka 'void (*)(unsigned int,  unsigned int)'} but argument is of type 'void (*)(UINT,  UINT8)' {aka 'void (*)(unsigned int,  unsigned char)'}
  107 | BRESULT iocore_attachout(UINT port, IOOUT func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:477:32: error: passing argument 2 of 'iocore_attachout' from incompatible pointer type [-Wincompatible-pointer-types]
  477 |         iocore_attachout(0xda, amd_oda);
      |                                ^~~~~~~
      |                                |
      |                                void (*)(UINT,  UINT8) {aka void (*)(unsigned int,  unsigned char)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:107:43: note: expected 'IOOUT' {aka 'void (*)(unsigned int,  unsigned int)'} but argument is of type 'void (*)(UINT,  UINT8)' {aka 'void (*)(unsigned int,  unsigned char)'}
  107 | BRESULT iocore_attachout(UINT port, IOOUT func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:478:32: error: passing argument 2 of 'iocore_attachout' from incompatible pointer type [-Wincompatible-pointer-types]
  478 |         iocore_attachout(0xdb, amd_odb);
      |                                ^~~~~~~
      |                                |
      |                                void (*)(UINT,  UINT8) {aka void (*)(unsigned int,  unsigned char)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:107:43: note: expected 'IOOUT' {aka 'void (*)(unsigned int,  unsigned int)'} but argument is of type 'void (*)(UINT,  UINT8)' {aka 'void (*)(unsigned int,  unsigned char)'}
  107 | BRESULT iocore_attachout(UINT port, IOOUT func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:479:32: error: passing argument 2 of 'iocore_attachout' from incompatible pointer type [-Wincompatible-pointer-types]
  479 |         iocore_attachout(0xdc, amd_odc);
      |                                ^~~~~~~
      |                                |
      |                                void (*)(UINT,  UINT8) {aka void (*)(unsigned int,  unsigned char)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:107:43: note: expected 'IOOUT' {aka 'void (*)(unsigned int,  unsigned int)'} but argument is of type 'void (*)(UINT,  UINT8)' {aka 'void (*)(unsigned int,  unsigned char)'}
  107 | BRESULT iocore_attachout(UINT port, IOOUT func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:480:32: error: passing argument 2 of 'iocore_attachout' from incompatible pointer type [-Wincompatible-pointer-types]
  480 |         iocore_attachout(0xde, amd_ode);
      |                                ^~~~~~~
      |                                |
      |                                void (*)(UINT,  UINT8) {aka void (*)(unsigned int,  unsigned char)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:107:43: note: expected 'IOOUT' {aka 'void (*)(unsigned int,  unsigned int)'} but argument is of type 'void (*)(UINT,  UINT8)' {aka 'void (*)(unsigned int,  unsigned char)'}
  107 | BRESULT iocore_attachout(UINT port, IOOUT func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:482:32: error: passing argument 2 of 'iocore_attachinp' from incompatible pointer type [-Wincompatible-pointer-types]
  482 |         iocore_attachinp(0xda, amd_ida);
      |                                ^~~~~~~
      |                                |
      |                                UINT8 (*)(UINT) {aka unsigned char (*)(unsigned int)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:109:43: note: expected 'IOINP' {aka 'unsigned int (*)(unsigned int)'} but argument is of type 'UINT8 (*)(UINT)' {aka 'unsigned char (*)(unsigned int)'}
  109 | BRESULT iocore_attachinp(UINT port, IOINP func);
      |                                     ~~~~~~^~~~
/tmp/makepkg/np2kai-git/src/NP2kai/cbus/amd98.c:483:32: error: passing argument 2 of 'iocore_attachinp' from incompatible pointer type [-Wincompatible-pointer-types]
  483 |         iocore_attachinp(0xdb, amd_idb);
      |                                ^~~~~~~
      |                                |
      |                                UINT8 (*)(UINT) {aka unsigned char (*)(unsigned int)}
/tmp/makepkg/np2kai-git/src/NP2kai/io/iocore.h:109:43: note: expected 'IOINP' {aka 'unsigned int (*)(unsigned int)'} but argument is of type 'UINT8 (*)(UINT)' {aka 'unsigned char (*)(unsigned int)'}
  109 | BRESULT iocore_attachinp(UINT port, IOINP func);
      |                                     ~~~~~~^~~~
At top level:
cc1: note: unrecognized command-line option '-Wno-incompatible-function-pointer-types' may have been intended to silence earlier diagnostics
```

**Comment by cmitu** [comment]
@sl1pkn07 the errors you have are not related to the changes introduced in this PR. 

They're probably caused by the `-Wincompatible-pointer-types` option which is set by your compiler/environment - similar to the errors already reported in https://github.com/AZO234/NP2kai/issues/181.

**Comment by sl1pkn07** [comment]
yes, probably, if -Wno-incompatible-function-pointer-types only work for macos, then maybe need brazed by "if define __MACOS__" or something similar for silence the warning in other OSes

greetings

**Pull request merged**
