### PR TITLE
Update for GCW0

### PR DESCRIPTION
**Pull request by madIlama**
Compiling for sdl2/gcw0 target in latest master failing for me

Looking at makefile it miss compiler flag gnu11
Plus,I add instruction for SDL2 toolchain location,since there are more newer branch of this target come to released

This is my first PR,please correct me if i am doing mistake
Thank You

### CODE REVIEW

**Comment by AZO234** [comment]
Wow thanks.

Probably other functions disabled.
(I don't have GCW0, I can't check.)

There is a request.
Would you like to add -D options like Makefile.libretro?

**Comment by madIlama** [comment]
Thanks for quick reply,

- For just building .opk ,you can try using pre-built toolchain binary here
http://www.gcw-zero.com/develop
even though,i am using newer source for my specific device (https://github.com/tonyjih/RG350_buildroot ,it was newer clone of gcw0,you can use it too),but i think for now we should stick to standard gcw0 toolchain

- Actually i have been tinkering with your -D flags,especially newer one like `SUPPORT_FAST_MEMORYCHECK` which compiled,build and executed just fine.
I will try to match with libretro as your suggestion and will report ASAP

**Comment by AZO234** [comment]
Ya. Thank you for a lot your trying.
Can I merge current your commit code? Or you more tune up?

(I thank toolchain for GCW, use crosstool-ng.)

**Comment by AZO234** [comment]
I could build with toolchain you said.
I modified around a bit.

- When after build, make .opk file.
- I set two Makefile for GCW0.
  Makefile.gcw0 : PC9801(i286 spec) -> np2kai.opk
  Makefile21.gcw0 : PC9821(IA-32 spec) -> np21kai.opk
  and different with generate default.gcw0.desktop.
- Cleaning with make

Anyway I can't check runnning. Please try binaries.

Regard.

**Comment by AZO234** [comment]
Now, I merge this.
Thank you!!

**Pull request merged**
