### PR TITLE
Joy2Key Mapping Core Option.

### PR DESCRIPTION
**Pull request by Tatsuya79**
Option to use the Joypad to call some pre-defined keyboard keys.

Useful for Touhou 1 & 2 that don't use the joypad at all.
I chose the keys for those games and then added some. 
That can be changed if you have any other game in mind that would need different keys.

It disables the keyboard when activated.
I wanted to keep the keyboard active but it causes some (strange) problems.

Seems to work fine with the Joy2Mouse option.

### CODE REVIEW

**Comment by AZO234** [comment]
I mind about this(Joy2Key) function too.
Wow, great work. Thank you!

I think general PC98 game's keymap follows
Z : B button
X : A button
Left or tenkey 4 : left
Right or tenkey 6 : right
Up or tenkey 8 : up
Down or tenkey 2 : down

And it probably need Return and Escape.

Your code is fully satisfied.
I would like to commit immediately.
Do you have any other ideas?

**Comment by Tatsuya79** [comment]
I thought this list of keys you just gave is the usual basis too.
We can change the other ones later if we think of anything useful.

So you can merge it, sure.

**Comment by AZO234** [comment]
Thanks.
I hope that more Touhou fans enjoy.
(When I knew Touhou 1, I was Junior High School student...)

**Comment by Tatsuya79** [comment]
I was in high school too here in France.
I didn't know about Touhou but was listening to X Japan - Dahlia though. 🌹

**Pull request merged**
